const data = [

    {
        id: 1,
        firstName: 'John',
        middleName: 'Doe',
        lastName: 'Smith',
        address: '123 Main St',
        city: 'Anytown',
        state: 'CA',
        country: 'USA',
    },
    {
        id: 1,
        firstName: 'John',
        middleName: 'Doe',
        lastName: 'Smith',
        address: '123 Main St',
        city: 'Anytown',
        state: 'CA',
        country: 'USA',
    },
    {
        id: 1,
        firstName: 'John',
        middleName: 'Doe',
        lastName: 'Smith',
        address: '123 Main St',
        city: 'Anytown',
        state: 'CA',
        country: 'USA',
    },
    {
        id: 1,
        firstName: 'John',
        middleName: 'Doe',
        lastName: 'Smith',
        address: '123 Main St',
        city: 'Anytown',
        state: 'CA',
        country: 'USA',
    },
    {
        id: 1,
        firstName: 'Sara',
        middleName: 'Doe',
        lastName: 'Smith',
        address: '123 Main St',
        city: 'Anytown',
        state: 'CA',
        country: 'USA',
    },
    {
        id: 1,
        firstName: 'John',
        middleName: 'Doe',
        lastName: 'Smith',
        address: '123 Main St',
        city: 'Anytown',
        state: 'CA',
        country: 'USA',
    },
    {
        id: 1,
        firstName: 'John',
        middleName: 'Doe',
        lastName: 'Smith',
        address: '123 Main St',
        city: 'Anytown',
        state: 'CA',
        country: 'USA',
    },
    {
        id: 1,
        firstName: 'John',
        middleName: 'Doe',
        lastName: 'Smith',
        address: '123 Main St',
        city: 'Anytown',
        state: 'CA',
        country: 'USA',
    },
    {
        id: 1,
        firstName: 'John',
        middleName: 'Doe',
        lastName: 'Smith',
        address: '123 Main St',
        city: 'Anytown',
        state: 'CA',
        country: 'USA',
    },
    {
        id: 1,
        firstName: 'John',
        middleName: 'Doe',
        lastName: 'Smith',
        address: '123 Main St',
        city: 'Anytown',
        state: 'CA',
        country: 'USA',
    },
    {
        id: 1,
        firstName: 'John',
        middleName: 'Doe',
        lastName: 'Smith',
        address: '123 Main St',
        city: 'Anytown',
        state: 'CA',
        country: 'USA',
    }
];

// Assuming you want the data array to be used as Person type
export { data };

